services:
  a0db:
    image: postgres:17
    container_name: a0db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdb:/var/lib/postgresql/data
    networks:
      - stack
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  electric:
    container_name: electric
    image: electricsql/electric:latest
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@a0db:5432/postgres?sslmode=disable
      - ELECTRIC_PORT=3001
      - ELECTRIC_ALLOW_SHAPE_DELETION=1
      - ELECTRIC_INSECURE=true
    networks:
      - stack
    ports:
      - "3001:3001"
    depends_on:
      - a0db

volumes:
  pgdb:

networks:
  stack:
